#interfaces da parte 2.
from abc import ABC, abstractmethod


class Dicionario(ABC):
    @abstractmethod
    def inserir(self, chave, valor): ...
    @abstractmethod
    def buscar(self, chave): ...
    @abstractmethod
    def remover(self, chave): ...


class TrieInterface(ABC):
    @abstractmethod
    def inserir(self, palavra, valor): ...
    @abstractmethod
    def buscar(self, palavra): ...
    @abstractmethod
    def buscar_prefixo(self, prefixo): ...
    @abstractmethod
    def remover(self, palavra): ...
    @abstractmethod
    def nos_visitados(self): ...


class ArvoreBInterface(ABC):
    @abstractmethod
    def inserir(self, chave, valor): ...
    @abstractmethod
    def buscar(self, chave): ...
    @abstractmethod
    def buscar_faixa(self, minimo, maximo): ...
    @abstractmethod
    def remover(self, chave): ...
    @abstractmethod
    def total_splits(self): ...
    @abstractmethod
    def altura(self): ...